version: '3.8'
services:
  mysql:
    container_name: 'mysql-magalu'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=magaludb'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'  # Mapear a porta 3307 do host para a 3306 do contêiner
    networks:
      - magalu-network
    restart: always

networks:
  magalu-network:
    driver: bridge
